// LEETCODE 3474. Lexicographically Smallest Generated String

// You are given two strings, str1 and str2, of lengths n and m, respectively.

// A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:

// If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
// If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
// Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".

 

// Example 1:

// Input: str1 = "TFTF", str2 = "ab"

// Output: "ababa"

// Explanation:

// The table below represents the string "ababa"
// Index	T/F	Substring of length m
// 0	'T'	"ab"
// 1	'F'	"ba"
// 2	'T'	"ab"
// 3	'F'	"ba"
// The strings "ababa" and "ababb" can be generated by str1 and str2.

// Return "ababa" since it is the lexicographically smaller string.

// Example 2:

// Input: str1 = "TFTF", str2 = "abc"

// Output: ""

// Explanation:

// No string that satisfies the conditions can be generated.

// Example 3:

// Input: str1 = "F", str2 = "d"

// Output: "a"

 

// Constraints:

// 1 <= n == str1.length <= 104
// 1 <= m == str2.length <= 500
// str1 consists only of 'T' or 'F'.
// str2 consists only of lowercase English characters.


// 🚀 Approach
// Create a string of length n + m - 1 filled with *. Also track which positions are flexible (canChange).
// Process T positions:
//     For each index i where str1[i] == T, overlay str2 starting at i.
//     If there’s a conflict (existing character differs from str2[j]), return "".
// Fill remaining positions:
//     Replace all * with a (lexicographically smallest). Mark them as changeable.
// Process F positions:
//     For each index i where str1[i] == F, check if word[i..i + m -1] == str2.
//     If yes, break the match by changing the rightmost changeable position in that substring to b.
//     If no changeable position exists, return "".
// After processing all rules, return the constructed word.

// 🕛 Complexity
// Time complexity: O(n * m)
// Space complexity: O(N) , N = n + m - 1









class Solution {
    public String generateString(String str1, String str2) {
        int n = str1.length();
        int m = str2.length();
        int N = n + m - 1;

        char[] word = new char[N];
        boolean[] canChange = new boolean[N];

        // Fill with placeholder
        for (int i = 0; i < N; i++) {
            word[i] = '$';
        }

        // Step 1: Process 'T'
        for (int i = 0; i < n; i++) {
            if (str1.charAt(i) == 'T') {
                int idx = i;
                for (int j = 0; j < m; j++) {
                    if (word[idx] != '$' && word[idx] != str2.charAt(j)) {
                        return "";
                    }
                    word[idx] = str2.charAt(j);
                    idx++;
                }
            }
        }

        // Step 2: Fill remaining with 'a'
        for (int i = 0; i < N; i++) {
            if (word[i] == '$') {
                word[i] = 'a';
                canChange[i] = true;
            }
        }

        // Step 3: Process 'F'
        for (int i = 0; i < n; i++) {
            if (str1.charAt(i) == 'F') {

                if (isEqual(word, str2, i, m)) {
                    boolean changed = false;

                    for (int k = i + m - 1; k >= i; k--) {
                        if (canChange[k]) {
                            word[k] = 'b';  // minimal change
                            canChange[k] = false;
                            changed = true;
                            break;
                        }
                    }

                    if (!changed) return "";
                }
            }
        }

        return new String(word);
    }

    private boolean isEqual(char[] word, String str2, int i, int m) {
        for (int j = 0; j < m; j++) {
            if (word[i] != str2.charAt(j)) return false;
            i++;
        }
        return true;
    }
}